/**
 * Webida Restful API
 * Restful API for Webida clients to use server's data & features
 *
 * OpenAPI spec version: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DirEntry', 'model/Stats'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DirEntry'), require('./Stats'));
  } else {
    // Browser globals (root is window)
    if (!root.WebidaRestfulApi) {
      root.WebidaRestfulApi = {};
    }
    root.WebidaRestfulApi.DirEntry = factory(root.WebidaRestfulApi.ApiClient, root.WebidaRestfulApi.DirEntry, root.WebidaRestfulApi.Stats);
  }
}(this, function(ApiClient, DirEntry, Stats) {
  'use strict';




  /**
   * The DirEntry model module.
   * @module model/DirEntry
   * @version 0.7.0
   */

  /**
   * Constructs a new <code>DirEntry</code>.
   * a directory entry (file or directory) with children that represents a (sub) tree
   * @alias module:model/DirEntry
   * @class
   * @param name {String} 
   * @param stats {module:model/Stats} 
   * @param children {Array.<module:model/DirEntry>} 
   */
  var exports = function(name, stats, children) {
    var _this = this;

    _this['name'] = name;
    _this['stats'] = stats;
    _this['children'] = children;
  };

  /**
   * Constructs a <code>DirEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DirEntry} obj Optional instance to populate.
   * @return {module:model/DirEntry} The populated <code>DirEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('stats')) {
        obj['stats'] = Stats.constructFromObject(data['stats']);
      }
      if (data.hasOwnProperty('children')) {
        obj['children'] = ApiClient.convertToType(data['children'], [DirEntry]);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/Stats} stats
   */
  exports.prototype['stats'] = undefined;
  /**
   * @member {Array.<module:model/DirEntry>} children
   */
  exports.prototype['children'] = undefined;



  return exports;
}));


