/**
 * Webida Restful API
 * Restful API for Webida clients to use server's data & features
 *
 * OpenAPI spec version: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WebidaRestfulApi) {
      root.WebidaRestfulApi = {};
    }
    root.WebidaRestfulApi.ExecutionResult = factory(root.WebidaRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ExecutionResult model module.
   * @module model/ExecutionResult
   * @version 0.6.0
   */

  /**
   * Constructs a new <code>ExecutionResult</code>.
   * execution response
   * @alias module:model/ExecutionResult
   * @class
   * @param stdout {String} standard out of child process.
   * @param stderr {String} standard error of child process.
   */
  var exports = function(stdout, stderr) {
    var _this = this;


    _this['stdout'] = stdout;
    _this['stderr'] = stderr;
  };

  /**
   * Constructs a <code>ExecutionResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExecutionResult} obj Optional instance to populate.
   * @return {module:model/ExecutionResult} The populated <code>ExecutionResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
      if (data.hasOwnProperty('stdout')) {
        obj['stdout'] = ApiClient.convertToType(data['stdout'], 'String');
      }
      if (data.hasOwnProperty('stderr')) {
        obj['stderr'] = ApiClient.convertToType(data['stderr'], 'String');
      }
    }
    return obj;
  }

  /**
   * error message when execution failed.
   * @member {String} error
   */
  exports.prototype['error'] = undefined;
  /**
   * standard out of child process.
   * @member {String} stdout
   */
  exports.prototype['stdout'] = undefined;
  /**
   * standard error of child process.
   * @member {String} stderr
   */
  exports.prototype['stderr'] = undefined;



  return exports;
}));


