/**
 * Webida Restful API
 * Restful API for Webida clients to use server's data & features
 *
 * OpenAPI spec version: 0.7.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WebidaRestfulApi) {
      root.WebidaRestfulApi = {};
    }
    root.WebidaRestfulApi.RemoteAccess = factory(root.WebidaRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RemoteAccess model module.
   * @module model/RemoteAccess
   * @version 0.7.1
   */

  /**
   * Constructs a new <code>RemoteAccess</code>.
   * Access information of remote workspace in remote server
   * @alias module:model/RemoteAccess
   * @class
   * @param name {String} display text of remote workspace. can be different from original name.
   * @param serverUrl {String} the url of remote server. Should have no path/query parameters, even \"/\" in path.
   * @param workspaceId {String} the id of remote workspace, read from remote server
   * @param masterToken {String} master token to access service, issued from remote server
   */
  var exports = function(name, serverUrl, workspaceId, masterToken) {
    var _this = this;

    _this['name'] = name;
    _this['serverUrl'] = serverUrl;
    _this['workspaceId'] = workspaceId;

    _this['masterToken'] = masterToken;
  };

  /**
   * Constructs a <code>RemoteAccess</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RemoteAccess} obj Optional instance to populate.
   * @return {module:model/RemoteAccess} The populated <code>RemoteAccess</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('serverUrl')) {
        obj['serverUrl'] = ApiClient.convertToType(data['serverUrl'], 'String');
      }
      if (data.hasOwnProperty('workspaceId')) {
        obj['workspaceId'] = ApiClient.convertToType(data['workspaceId'], 'String');
      }
      if (data.hasOwnProperty('workspacePath')) {
        obj['workspacePath'] = ApiClient.convertToType(data['workspacePath'], 'String');
      }
      if (data.hasOwnProperty('masterToken')) {
        obj['masterToken'] = ApiClient.convertToType(data['masterToken'], 'String');
      }
    }
    return obj;
  }

  /**
   * display text of remote workspace. can be different from original name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * the url of remote server. Should have no path/query parameters, even \"/\" in path.
   * @member {String} serverUrl
   */
  exports.prototype['serverUrl'] = undefined;
  /**
   * the id of remote workspace, read from remote server
   * @member {String} workspaceId
   */
  exports.prototype['workspaceId'] = undefined;
  /**
   * Full path of remote workspace, read from remote server. this property will be removed when clients are able to work without \"named root directory\" in workspace fs tree.
   * @member {String} workspacePath
   */
  exports.prototype['workspacePath'] = undefined;
  /**
   * master token to access service, issued from remote server
   * @member {String} masterToken
   */
  exports.prototype['masterToken'] = undefined;



  return exports;
}));


