/**
 * Webida Restful API
 * Minimal, Basic Webida Restful API definitions
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WebidaRestfulApi) {
      root.WebidaRestfulApi = {};
    }
    root.WebidaRestfulApi.Workspace = factory(root.WebidaRestfulApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Workspace model module.
   * @module model/Workspace
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>Workspace</code>.
   * A workspace in server
   * @alias module:model/Workspace
   * @class
   * @param id {String} the id of a workspace. usually same to file system id
   * @param name {String} display text of this workspace for UI
   * @param description {String} human readable description on this workspace
   * @param createdAt {Date} the time when this workspace is created (registered from local file system)
   * @param accessedAt {Date} the time when the last session on this workspace was made
   */
  var exports = function(id, name, description, createdAt, accessedAt) {
    var _this = this;

    _this['id'] = id;
    _this['name'] = name;
    _this['description'] = description;
    _this['createdAt'] = createdAt;
    _this['accessedAt'] = accessedAt;

  };

  /**
   * Constructs a <code>Workspace</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Workspace} obj Optional instance to populate.
   * @return {module:model/Workspace} The populated <code>Workspace</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('createdAt')) {
        obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
      }
      if (data.hasOwnProperty('accessedAt')) {
        obj['accessedAt'] = ApiClient.convertToType(data['accessedAt'], 'Date');
      }
      if (data.hasOwnProperty('workspacePath')) {
        obj['workspacePath'] = ApiClient.convertToType(data['workspacePath'], 'String');
      }
    }
    return obj;
  }

  /**
   * the id of a workspace. usually same to file system id
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * display text of this workspace for UI
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * human readable description on this workspace
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * the time when this workspace is created (registered from local file system)
   * @member {Date} createdAt
   */
  exports.prototype['createdAt'] = undefined;
  /**
   * the time when the last session on this workspace was made
   * @member {Date} accessedAt
   */
  exports.prototype['accessedAt'] = undefined;
  /**
   * absolute path of this workspace in server. (not always available)
   * @member {String} workspacePath
   */
  exports.prototype['workspacePath'] = undefined;



  return exports;
}));


